M48
; DRILL file {KiCad 9.0.7} date 2026-03-11T17:11:53-0500
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-03-11T17:11:53-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.900
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.810
%
G90
G05
T1
X155.352Y-75.319
X161.132Y-75.319
T2
X188.137Y-73.548
X190.956Y-74.574
T3
X80.0Y-100.0
M30
